SECRET_KEY: "44b6295def9f61c17c1b0303bb3af65d0bb6efba2648f5a841ce4dfad3ce19cc"
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 60
EMAIL_OTP_EXPIRATION_MINUTES: 5

SMTP_SETTINGS:
  host: "smtp-mail.outlook.com"
  port: 587
  username: "rahul.raj@ag-technologies.com"
  password: ""

DATABASE:
  DB_DRIVER: "SQL Server"
  DB_HOST: "VBINBRSUTDB01"
  DB_PORT: 2433
  DB_USER: "BRS"
  DB_PASSWORD: "Axis@1234"
  DB_NAME: "BRSUAT"
  DB_TRUSTED_CONNECTION: "yes"
  DB_TIMEOUT: 60

LDAP:
  # Uncomment this for production
  LDAP_SERVER_URL: "ldap://10.0.42.62"
  LDAP_PORT: 389
  LDAP_BIND_DN: "CN=AFLBRSADAPUL53,OU=Service Accounts,DC=axisb,DC=com"
  LDAP_BIND_PASSWORD: "Maharashtra@123"
  LDAP_BASE_DN: "DC=axisb,DC=com"
  LDAP_USER_SEARCH_FILTER: "(sAMAccountName={username})"
  LDAP_USER_ATTRIBUTES: "cn,sAMAccountName,mail,sn,givenName"

  # Uncomment this for local testing
  #  LDAP_SERVER_URL: "ldap://localhost"
  #  LDAP_PORT: 389
  #  LDAP_BIND_DN: "cn=admin,dc=myldap,dc=local"
  #  LDAP_BIND_PASSWORD: "admin"
  #  LDAP_BASE_DN: "dc=myldap,dc=local"
  #  LDAP_USER_SEARCH_FILTER: "(&(objectClass=person)(uid={username}))"
  #  LDAP_USER_ATTRIBUTES: ["cn", "uid", "mail", "sn"]  # Attributes to fetch

FRONTEND_URL: 'http://localhost:3000'

